# Use the official Node.js runtime as the base image
FROM node:18 as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and yarn.lock to the working directory
COPY package.json yarn.lock ./

# Install dependencies
RUN yarn --network-timeout 300000

# Copy the entire application code to the container
COPY . .

# Copy the appropriate .env file based on the NODE_ENV
ARG NODE_ENV
COPY .env.${NODE_ENV} .env

# Build the React app with Vite
CMD ["yarn", "dev","--host", "0.0.0.0"]
