name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Run yarn build on GitHub Actions
      run: |
        yarn install
        yarn build
        ls -la

    - name: Copy dist to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        source: "dist"
        target: "/usr/share/nginx/html"

    - name: Copy files to running container on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_HOST}}
        key: ${{secrets.SERVER_SSH_KEY}}
        username: ${{secrets.SERVER_USERNAME}}
        script: |
          cd /var/www/html
          cp -r dist/* .
          rm -rf dist
          ls -la
          sudo service nginx restart
          echo "finish"
