
name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy app
      uses: appleboy/ssh-action@ve.1.2
    with:
      host: ${{secrets.SERVER_HOST}}
      key: ${{secrets.SERVER_SSH_KEY}}
      username: ${{secrets.SERVER_USERNAME}}
      script: |
        mkdir test
        cd test
        echo "finish"
