name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build --file Dockerfile.prod --build-arg NODE_ENV=production -t blog_frontend .

    - name: Copy files to running container
      run: |
        docker cp dist/. root@${{ secrets.SERVER_HOST }}:/usr/share/nginx/html/
      env:
        DOCKER_HOST: ssh://root@${{ secrets.SERVER_HOST }}
        DOCKER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

    - name: Restart container on server
      run: |
        ssh -i ${{ secrets.SERVER_SSH_KEY }} root@${{ secrets.SERVER_HOST }} 'docker compose restart blog_frontend'
