name: Deploy to Server

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Build Docker image
      run: docker build --file Dockerfile.prod --build-arg NODE_ENV=production -t blog_frontend .
    - name: Extract Dist from Docker Image
      run: docker create --name dummy blog_frontend && docker cp dummy:/app/dist . && docker rm -f dummy
    - name: Copy files to running container on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{secrets.SERVER_HOST}}
        key: ${{secrets.SERVER_SSH_KEY}}
        username: ${{secrets.SERVER_USERNAME}}
        script: |
          docker cp dist/. blog_frontend:/usr/share/nginx/html/
          docker compose restart blog_frontend
          echo "finish"
